### ISSUE TITLE
Replacing period to comma.

### ISSUE THREAD

**Issue by filipe-cauduro** [ecirpnaes/SimpleDataScripter#3]
When I try to script, happens to replace the period from a decimal column to a comma, making the select list have more columns than the insert into statement.

I'm using the v0.1.3.

I don't know how can I get you more information, if you'd like something just let me know.

**Comment by ecirpnaes** [comment]
If you can supply me with the table schema and some sample data, that would be great.

**Comment by YomaSun** [comment]
I have the same problem here on a german database, u cant see it in sql schema.
MS sql server management studio has the same problem btw.

`
float: 1.23 in english
is
float: 1,23 in german
so we got more columns
we need convert

this works:
create table [#temptblB] (
[number1] [decimal] (18,2) NULL
);
insert [#temptblB] ([number1])
select 422.74

this works not:
insert [#temptblB] ([number1])
select 422,74
`

**Comment by ecirpnaes** [comment]
Yup. I believe this is an issue with the database collation. I'll have to
look into checking that and doing a covert on it before the insert.

**Comment by YomaSun** [comment]
My values are:
`
select SERVERPROPERTY('collation')
--> Latin1_General_CI_AS
`
windows country property: german

**Comment by ecirpnaes** [comment]
I've pushed a fix that should work for you. It's not released yet, but feel
free to grab it and let me know if it works for you. And thanks for
reporting the issue. Nice to know people are using the extension. (MS does
not release stats for Azure Extensions).

Here's the release.
https://github.com/ecirpnaes/SimpleDataScripter/releases/tag/0.1.4

**Comment by YomaSun** [comment]
great thanks, it worked good

for interesting:
why you use the insert/select syntax, it is faster than the default insert?

**Comment by ecirpnaes** [comment]
Whether it's faster or not depends on many factors, such as number of rows,
type of data, and how you have your database set up for transaction
logging. That said, I use the insert/select syntax mainly to keep the file
size down, because using the "insert into values (...) syntax effectively
double the amount of text scripted out. If you have a lot of rows it's very
easy to run out of memory trying to load the script.

My aim with the extension was to build something simple and lightweight and
easy to use. I could have built something with lots of options, like
choosing how to script, saving data to file system, etc.. but this was not
really the aim of the extension.

**Comment by YomaSun** [comment]
Ah ok thanks. Yes shorter is better.
